### ISSUE TITLE
An unexpected failure occurred: Data plan execution failed with message Unable to reconnect to database: Execution Timeo ut Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding..

### ISSUE THREAD

**Issue by PaulHeisterkamp** [d365collaborative/d365fo.tools#276]
I´m getting an exception related to a timeout setting when I want to import a very large bacpac to a Tier1 environment.
To fix this problem we have to set the propertie CommandTimeout to 0 (/p:CommandTimeout=0)
The error looks like this:

Importing to database 'AxDB_Prod_20190508' on server 'localhost'.
Creating deployment plan
Initializing deployment
Verifying deployment plan
Analyzing deployment plan
Importing package schema and data into database
Updating database
An unexpected failure occurred: Data plan execution failed with message Unable to reconnect to database: Execution Timeo
ut Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding..

Unhandled Exception: Microsoft.SqlServer.Dac.Data.DataException: Data plan execution failed with message Unable to recon
nect to database: Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the ser
ver is not responding. ---> Microsoft.Data.Tools.Schema.Sql.SchemaModel.SqlReverseEngineerException: Unable to reconnect
 to database: Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server
is not responding. ---> System.Data.SqlClient.SqlException: Execution Timeout Expired.  The timeout period elapsed prior
 to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception: The wait ope
ration timed out
   --- End of inner exception stack trace ---
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInA
ction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectio
nLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, B
ulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TrySetMetaData(_SqlMetaDataSet metaData, Boolean moreInfo)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, B
ulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at System.Data.SqlClient.SqlDataReader.Read()
   at Microsoft.Data.Tools.Schema.Sql.SchemaModel.ReverseEngineerPopulators.TopLevelElementPopulator`1.Populate(SqlRever
seEngineerRequest request, OrdinalSqlDataReader reader, ReverseEngineerOption option)
   --- End of inner exception stack trace ---
   at Microsoft.Data.Tools.Schema.Sql.SchemaModel.SqlReverseEngineerImpl.ExecutePopulatorsInPass(SqlReverseEngineerConne
ctionContext context, ReverseEngineerOption option, SqlReverseEngineerRequest request, Int32 totalCount, Tuple`2[] popul
atorsArray)
   at Microsoft.Data.Tools.Schema.Sql.SchemaModel.SqlReverseEngineerImpl.PopulateBatch(SqlReverseEngineerConnectionConte
xt context, SqlSchemaModel model, ReverseEngineerOption option, ErrorManager errorManager, SqlReverseEngineerRequest req
uest, SqlImportScope importScope)
   at Microsoft.Data.Tools.Schema.Sql.SchemaModel.SqlReverseEngineer.PopulateElements(SqlReverseEngineerConnectionContex
t context, DataSchemaModel model, ReverseEngineerOption option, ErrorManager errorManager, SqlImportScope importScope, S
qlReverseEngineerRequest[] requests)
   at Microsoft.Data.Tools.Schema.Sql.Deployment.Steps.DacBulkCopyStep.GetImportTableMetadata(ICollection`1 tables)
   at Microsoft.Data.Tools.Schema.Sql.Deployment.Steps.DacBulkCopyStep.Execute(IDbConnection conn, CancellationToken tok
en, LoggingContext loggingContext)
   at Microsoft.Data.Tools.Schema.Sql.Deployment.SqlPlanDeployment.Execute(DeploymentPlanHandle plan, SqlConnectionFacto
ry connectionFactory, String targetDatabaseName, Boolean IsAzureTarget, String databaseScriptPath, String masterScriptPa
th, CancellationToken cancelToken, LoggingContext loggingContext)
   at Microsoft.SqlServer.Dac.Deployment.PlanExecutor.Execute(DeploymentPlan plan, SqlConnectionFactory connectionFactor
y, Boolean isAzureTarget, LoggingContext loggingContext, CancellationToken cancelToken)
   --- End of inner exception stack trace ---
   at Microsoft.SqlServer.Dac.Deployment.PlanExecutor.Execute(DeploymentPlan plan, SqlConnectionFactory connectionFactor
y, Boolean isAzureTarget, LoggingContext loggingContext, CancellationToken cancelToken)
   at Microsoft.SqlServer.Dac.DeployOperation.UpdateDatabaseData(LoggingContext loggingContext, CancellationToken token)
   at Microsoft.SqlServer.Dac.DeployOperation.<>c__DisplayClass14.<>c__DisplayClass16.<CreatePlanExecutionOperation>b__1
3()
   at Microsoft.Data.Tools.Schema.Sql.Dac.OperationLogger.Capture(Action action)
   at Microsoft.SqlServer.Dac.DeployOperation.<>c__DisplayClass14.<CreatePlanExecutionOperation>b__12(Object operation,
CancellationToken token)
   at Microsoft.SqlServer.Dac.Operation.Microsoft.SqlServer.Dac.IOperation.Run(OperationContext context)
   at Microsoft.SqlServer.Dac.ReportMessageOperation.Microsoft.SqlServer.Dac.IOperation.Run(OperationContext context)
   at Microsoft.SqlServer.Dac.DeployOperation.Microsoft.SqlServer.Dac.IOperation.Run(OperationContext context)
   at Microsoft.SqlServer.Dac.OperationExtension.Execute(IOperation operation, DacLoggingContext loggingContext, Cancell
ationToken cancellationToken)
   at Microsoft.SqlServer.Dac.DacServices.InternalDeploy(IPackageSource packageSource, Boolean isDacpac, String targetDa
tabaseName, DacDeployOptions options, CancellationToken cancellationToken, DacLoggingContext loggingContext, Action`3 re
portPlanOperation, Boolean executePlan)
   at Microsoft.SqlServer.Dac.DacServices.ImportBacpac(BacPackage package, String targetDatabaseName, DacImportOptions i
mportOptions, Nullable`1 cancellationToken)
   at Microsoft.Data.Tools.Schema.CommandLineTool.Program.DoImportBacpacOperation(CommandLineArguments parsedArgs)
   at Microsoft.Data.Tools.Schema.CommandLineTool.Program.PerformAction(CommandLineArguments parsedArgs)
   at Microsoft.Data.Tools.Schema.CommandLineTool.Program.Run(String[] args)
   at Microsoft.Data.Tools.Schema.CommandLineTool.Program.Main(String[] args)

**Comment by Splaxi** [comment]
Will make sure it makes it with the next release!

**Comment by Splaxi** [comment]
Should be fixed in 0.5.35

**Comment by PaulHeisterkamp** [comment]
Nice, thanks!
