### ISSUE TITLE
Invoke-D365SDPInstall -> Unlock file before execution

### ISSUE THREAD

**Issue by Shind44** [d365collaborative/d365fo.tools#62]
If files are not unlock manually, command failed with obscur error message (see below)
 
I must execute this command before
Get-ChildItem C:\Temp\RunBook\ -Recurse | Unblock-File

maybe you can add this unblock command in our function to bypass this error

PS C:\Temp\RunBook> Invoke-D365SDPInstall -Path "C:\Temp\RunBook" -verbose -Command runall
VERBOSE: [07:44:36][Test-PathExists] Testing the path: C:\Temp\RunBook\DefaultTopologyData.xml
VERBOSE: [07:44:36][Test-PathExists] Testing the path: C:\Temp\RunBook\AXUpdateInstaller.exe
VERBOSE: [07:44:36][Invoke-D365SDPInstall] Running all manual steps in one single operation
VERBOSE: [07:44:36][Update-TopologyFile] Creating topology file: C:\Temp\RunBook\DefaultTopologyData.xml
Method invocation failed because [System.String] does not contain a method named 'RemoveAll'.
At line:13 char:5
+     $serviceModelList.RemoveAll()
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound

Exception calling "LoadFile" with "1" argument(s): "An attempt was made to load an assembly from a network location
which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the
.NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to
sandbox the assembly, please enable the loadFromRemoteSources switch. See
http://go.microsoft.com/fwlink/?LinkId=155569 for more information."
At line:16 char:5
+     [void][System.Reflection.Assembly]::LoadFile($instalInfoDll)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : NotSupportedException

Unable to find type [Microsoft.Dynamics.AX.AXInstallationInfo.AXInstallationInfo].
At line:18 char:15
+ ...   $models = [Microsoft.Dynamics.AX.AXInstallationInfo.AXInstallationI ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Dynam...nstallationInfo:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

Request for the permission of type 'System.Security.Permissions.FileIOPermission, mscorlib, Version=4.0.0.0, Culture=neu
tral, PublicKeyToken=b77a5c561934e089' failed.
   at System.Security.CodeAccessSecurityEngine.Check(Object demand, StackCrawlMark& stackMark, Boolean isPermSet)
   at System.Security.CodeAccessPermission.Demand()
   at System.Security.Permissions.FileIOPermission.QuickDemand(FileIOPermissionAccess access, AccessControlActions contr
ol, String[] fullPathList, Boolean checkForDuplicates, Boolean needFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShar
e share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolea
n useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy, RequestCachePolicy cac
hePolicy)
   at System.Xml.XmlUrlResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlSecureResolver.GetEntity(Uri absoluteUri, String role, Type ofObjectToReturn)
   at System.Xml.XmlTextReaderImpl.FinishInitUriString()
   at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
   at Microsoft.Dynamics.AX.AXUpdateInstallerBase.TopologyData.InitFromFile(String filePath)
   at Microsoft.Dynamics.AX.AXUpdateInstallerBase.AXUpdateInstallerBase.generate(String runbookID, String topologyFilePa
th, String serviceModelFilePath, String runbookFilePath, String updatePackageFilePath, IRunbookGenerator runbookGenerato
r, Boolean generateDVTStep)
   at Microsoft.Dynamics.AX.AXUpdateInstaller.Program.InstallUpdate(String[] args)
   at Microsoft.Dynamics.AX.AXUpdateInstaller.Program.Main(String[] args)
RunbookData File C:\Temp\RunBook\Runbook.xml not found, please verify you provide the right parameter name and file path

**Comment by skaue** [comment]
Did you unblock the zip before extracting the content?

**Comment by Shind44** [comment]
Hello Sakue,

yes that was the problem : i missed to unblock the zip , that why i propose to add the unblock function directly in the cmdlet to do not have to make this action manually.

It was just a suggestion, not an issue of the command

**Comment by Splaxi** [comment]
I have included it into the next release. Will close the issue when released.

**Comment by Shind44** [comment]
Thanks @Splaxi

**Comment by Splaxi** [comment]
Implemented in 0.4.18
